# Generated by Django 5.2.14 on 2026-05-24 20:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('passport_data', models.CharField(max_length=50, verbose_name='Паспортные данные')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название зала')),
                ('purpose', models.CharField(max_length=255, verbose_name='Назначение')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(choices=[('Любой', 'Любой'), ('Начальный', 'Начальный'), ('Средний', 'Средний'), ('Продвинутый', 'Продвинутый')], default='Любой', max_length=20, verbose_name='Уровень подготовки')),
                ('duration_min', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид абонемента')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Срок в днях')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая стоимость')),
                ('sessions_count', models.PositiveIntegerField(verbose_name='Количество занятий')),
                ('status', models.CharField(choices=[('Активен', 'Активен'), ('Архив', 'Архив')], default='Активен', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Стаж (лет)')),
                ('category', models.CharField(choices=[('Высшая', 'Высшая'), ('Первая', 'Первая'), ('Вторая', 'Вторая')], max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Итоговая стоимость')),
                ('club_name', models.CharField(default='FitClub Краснодар', max_length=255, verbose_name='Название клуба')),
                ('expiry_date', models.DateField(editable=False, verbose_name='Срок действия')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='gym.client', verbose_name='Клиент')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='gym.membership', verbose_name='Абонемент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('method', models.CharField(choices=[('Банковская карта', 'Банковская карта'), ('Наличные', 'Наличные'), ('Перевод', 'Перевод')], max_length=50, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('Ожидание', 'Ожидание'), ('Отменён', 'Отменён')], default='Успешно', max_length=20, verbose_name='Статус оплаты')),
                ('receipt_number', models.CharField(max_length=50, verbose_name='Номер чека')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gym.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Окончание')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='gym.hall', verbose_name='Зал')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='gym.lessontype', verbose_name='Тип занятия')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='gym.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Расписание занятия',
                'verbose_name_plural': 'Расписание занятий',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата записи')),
                ('status', models.CharField(choices=[('Запланировано', 'Запланировано'), ('Посещено', 'Посещено'), ('Отменено', 'Отменено')], default='Запланировано', max_length=20, verbose_name='Статус записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gym.client', verbose_name='Клиент')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gym.scheduleitem', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Запись на занятие',
                'verbose_name_plural': 'Записи на занятия',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Дата посещения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gym.client', verbose_name='Клиент')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gym.scheduleitem', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-visit_date'],
            },
        ),
    ]
